In [2]:
!pip install opendatasets --quiet

In [3]:
import opendatasets as od

In [4]:
od.download('https://www.kaggle.com/datasets/bhavikjikadara/fake-news-detection')

Skipping, found downloaded files in ".\fake-news-detection" (use force=True to force download)

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv('fake-news-detection/true.csv')
dff = pd.read_csv('fake-news-detection/fake.csv')

In [7]:
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [8]:
df.shape

(21417, 4)

In [9]:
df.describe()

,title,text,subject,date
count,21417,21417,21417,21417
unique,20826,21192,2,716
top,Factbox: Trump fills top jobs for his administ...,(Reuters) - Highlights for U.S. President Dona...,politicsNews,"December 20, 2017"
freq,14,8,11272,182

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB

In [11]:
df['date'].dtype

dtype('O')

In [12]:
df['date'] = pd.to_datetime(df['date'], errors = 'coerce')

In [13]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

In [14]:
dff.describe()

,title,text,subject,date
count,23481,23481,23481,23481
unique,17903,17455,6,1681
top,MEDIA IGNORES Time That Bill Clinton FIRED His...,,News,"May 10, 2017"
freq,6,626,9050,46

In [15]:
dff['subject'].value_counts()

subject
News               9050
politics           6841
left-news          4459
Government News    1570
US_News             783
Middle-east         778
Name: count, dtype: int64

In [16]:
df['subject'].value_counts()

subject
politicsNews    11272
worldnews       10145
Name: count, dtype: int64

In [17]:
df.isna().value_counts()

title  text   subject  date
False  False  False    False    21417
Name: count, dtype: int64

In [18]:
dff.isna().value_counts()

title  text   subject  date
False  False  False    False    23481
Name: count, dtype: int64

In [19]:
df.shape

(21417, 4)

In [20]:
dff.shape

(23481, 4)

In [21]:
df.drop(['date','subject'] , inplace = True ,axis = 1)
dff.drop(['date','subject'] , inplace = True , axis =1)

In [22]:
df['label'] = 1
dff['label'] = 0

In [23]:
def clean_text(text):

    if isinstance(text,str):
        text = text.lower()
        text = text.translate(str.maketrans('', '', string.punctuation))
        return text
    return text

In [24]:
df['text'] = df['text'].apply(clean_text)
dff['text'] = dff['text'].apply(clean_text)

In [25]:
df['text'].head()

0    washington reuters  the head of a conservative...
1    washington reuters  transgender people will be...
2    washington reuters  the special counsel invest...
3    washington reuters  trump campaign adviser geo...
4    seattlewashington reuters  president donald tr...
Name: text, dtype: object

In [26]:
dff['text'].head()

0    donald trump just couldn t wish all americans ...
1    house intelligence committee chairman devin nu...
2    on friday it was revealed that former milwauke...
3    on christmas day donald trump announced that h...
4    pope francis used his annual christmas day mes...
Name: text, dtype: object

In [27]:
help(str.translate)

Help on method_descriptor:

translate(self, table, /) unbound builtins.str method
    Replace each character in the string using the given translation table.

      table
        Translation table, which must be a mapping of Unicode ordinals to
        Unicode ordinals, strings, or None.

    The table must implement lookup/indexing via __getitem__, for instance a
    dictionary or list.  If this operation raises LookupError, the character is
    left untouched.  Characters mapped to None are deleted.

In [28]:
df_merged = pd.concat([df,dff],axis =0)
df_merged = df_merged.reset_index(drop = True)

In [29]:
df_merged.shape

(44898, 3)

In [30]:
df_merged['label'].value_counts()

label
0    23481
1    21417
Name: count, dtype: int64

In [31]:
df_merged.columns.value_counts()

title    1
text     1
label    1
Name: count, dtype: int64

In [32]:
X = df_merged['text']
y = df_merged['label']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3 , random_state = 42, stratify = y)

In [33]:
print(y_train.value_counts())
print(y_test.value_counts())

label
0    16436
1    14992
Name: count, dtype: int64
label
0    7045
1    6425
Name: count, dtype: int64

***TF-IDF***

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
#df_merged['text'] =  
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [36]:
vectorizer.get_feature_names_out()

array(['00', '000', '0000', ..., 'zzzzaaaacccchhh', 'zzzzzzzz', 'émigré'],
      dtype=object)

Its important to have the same number of columns in the tranformed test and train datasets

In [37]:
X_train_tfidf.shape

(31428, 188376)

In [38]:
X_test_tfidf.shape

(13470, 188376)

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score,precision_score,recall_score
model = LogisticRegression()
model.fit(X_train_tfidf,y_train)
y_pred = model.predict(X_test_tfidf)

print('F1 score : ', f1_score(y_pred,y_test))
print('Precision score : ', precision_score(y_pred,y_test))
print('Recall score : ', recall_score(y_pred,y_test))

F1 score :  0.9857996430511368
Precision score :  0.9886381322957198
Recall score :  0.982977406375735

In [40]:
import torch
class NewsDataset(torch.utils.data.Dataset):
    def __init__(self,texts,labels,tokenizer,seq_len):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.seq_len = seq_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self,idx):
        text = self.texts[idx]
        label = self.labels[idx]

        tokens = self.tokenizer.encode(text)

        if len(tokens) > self.seq_len:
            tokens = tokens[:self.seq_len]
        else:
            tokens = tokens + [0] * (self.seq_len - len(tokens))

        x = torch.tensor(tokens , dtype = torch.long)
        y = torch.tensor(label, dtype = torch.float)

        return x,y

In [41]:
texts = df_merged["text"].tolist()
labels = df_merged["label"].tolist()

In [42]:
class SimpleTokenizer:
    def __init__(self, vocab):
        self.vocab = vocab

    def encode(self, text):
        tokens = []
        for word in text.lower().split():
            tokens.append(self.vocab.get(word, self.vocab["<UNK>"]))
        return tokens

In [43]:
from collections import Counter

word_counts = Counter()

for text in texts:
    for word in text.lower().split():
        word_counts[word] += 1

In [44]:
# Returns the total number of words that appeared more than 5 times
total_frequent_count = sum(1 for count in word_counts.values() if count > 5)

print(total_frequent_count)

50447

In [45]:
vocab = {
    "<PAD>": 0,
    "<UNK>": 1
}

idx = 2
for word, count in word_counts.items():
    if count >= 5:
        vocab[word] = idx
        idx += 1

In [46]:
print(len(vocab))

56388

In [47]:
tokenizer = SimpleTokenizer(vocab)

In [48]:
encoded = tokenizer.encode(texts[0])
print(encoded[:20])
print(len(encoded))

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 4, 12, 13, 14, 15, 16, 17, 18, 7, 19]
745

In [49]:
print(tokenizer.encode("thisworddoesnotexist"))

[1]

In [50]:
dataset = NewsDataset(
    texts=texts,
    labels=labels,
    tokenizer=tokenizer,
    seq_len=300
)

In [51]:
x, y = dataset[0]

print(x.shape, x.dtype)
print(y, y.dtype)

torch.Size([300]) torch.int64
tensor(1.) torch.float32

In [52]:
print(x[:20])      # first 20 token IDs
print(x[-20:])     # last 20 token IDs

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  4, 12, 13, 14, 15, 16, 17, 18,
         7, 19])
tensor([185, 186,  23, 187,  47, 188, 132, 156, 189, 190,  12,  46, 191, 192,
        141,  31, 193, 192, 141,   4])

In [53]:
from torch.utils.data import DataLoader

loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True
)

In [54]:
batch_x, batch_y = next(iter(loader))

print(batch_x.shape, batch_x.dtype)
print(batch_y.shape, batch_y.dtype)

torch.Size([32, 300]) torch.int64
torch.Size([32]) torch.float32

In [55]:
import torch.nn as nn

vocab_size = len(vocab)      # ~30k
embed_dim = 100

embedding = nn.Embedding(
    num_embeddings=vocab_size,
    embedding_dim=embed_dim
)

In [56]:
embedded_x = embedding(batch_x)

print(embedded_x.shape, embedded_x.dtype)

torch.Size([32, 300, 100]) torch.float32

In [57]:
hidden_dim = 128

lstm = nn.LSTM(
    input_size=embed_dim,
    hidden_size=hidden_dim,
    batch_first=True
)

In [58]:
out, (h_n, c_n) = lstm(embedded_x)

print(out.shape)
print(h_n.shape)

torch.Size([32, 300, 128])
torch.Size([1, 32, 128])

In [59]:
final_repr = h_n[0]
print(final_repr.shape)

torch.Size([32, 128])

In [60]:
classifier = nn.Linear(hidden_dim, 1)

logits = classifier(final_repr)
print(logits.shape)

torch.Size([32, 1])

In [61]:
criterion = nn.BCEWithLogitsLoss()

In [62]:
optimizer = torch.optim.Adam(
    list(embedding.parameters()) +
    list(lstm.parameters()) +
    list(classifier.parameters()),
    lr=1e-3
)

In [63]:
# Forward pass (already done)
logits = classifier(final_repr)

# Loss
loss = criterion(logits.squeeze(), batch_y)

# Backprop
optimizer.zero_grad()
loss.backward()
optimizer.step()

'''
zero_grad(),Clear previous memory.
loss.backward(),Calculate the error direction.
step(),Move the weights.'''

print(loss.item())

0.6887754201889038

In [64]:
embedding.eval()
lstm.eval()
classifier.eval()

Linear(in_features=128, out_features=1, bias=True)

In [65]:
from torch.utils.data import random_split, DataLoader

dataset_size = len(dataset)
train_size = int(0.8 * dataset_size)
test_size = dataset_size - train_size

train_dataset, test_dataset = random_split(
    dataset,
    [train_size, test_size]
)

In [66]:
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

In [67]:
import torch.nn as nn

vocab_size = len(vocab)
embed_dim = 100
hidden_dim = 128

embedding = nn.Embedding(vocab_size, embed_dim)
lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
classifier = nn.Linear(hidden_dim, 1)

criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(
    list(embedding.parameters()) +
    list(lstm.parameters()) +
    list(classifier.parameters()),
    lr=1e-3
)

In [68]:
num_epochs = 5

for epoch in range(num_epochs):
    total_loss = 0

    for batch_x, batch_y in train_loader:

        embedded_x = embedding(batch_x)
        out, (h_n, _) = lstm(embedded_x)
        final_repr = h_n[0]
        logits = classifier(final_repr)

        loss = criterion(logits.squeeze(), batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}, Train Loss: {total_loss/len(train_loader)}")

Epoch 1, Train Loss: 0.4848302566410703
Epoch 2, Train Loss: 0.3328019715347995
Epoch 3, Train Loss: 0.41793082058031644
Epoch 4, Train Loss: 0.04695523973887758
Epoch 5, Train Loss: 0.013827317663844102

In [69]:
embedding.eval()
lstm.eval()
classifier.eval()

correct = 0
total = 0

import torch
with torch.no_grad():
    for batch_x, batch_y in test_loader:

        embedded_x = embedding(batch_x)
        out, (h_n, _) = lstm(embedded_x)
        final_repr = h_n[0]
        logits = classifier(final_repr)

        preds = (torch.sigmoid(logits).squeeze() >= 0.5).float()

        correct += (preds == batch_y).sum().item()
        total += batch_y.size(0)

accuracy = correct / total
print("Test Accuracy:", accuracy)

Test Accuracy: 0.994988864142539

In [81]:
import torch

def predict(text, tokenizer, embedding, lstm, classifier, device="cpu"):
    embedding.eval()
    lstm.eval()
    classifier.eval()

    with torch.no_grad():
        # 1. text -> list of token ids
        token_ids = tokenizer.encode(text)              # list[int]

        # 2. list -> tensor + batch dimension
        batch_x = torch.tensor(token_ids, dtype=torch.long)
        batch_x = batch_x.unsqueeze(0)                   # [1, seq_len]
        batch_x = batch_x.to(device)

        # 3. forward pass (same as evaluation)
        embedded_x = embedding(batch_x)
        out, (h_n, _) = lstm(embedded_x)
        final_repr = h_n[0]
        logits = classifier(final_repr)

        # 4. sigmoid + threshold
        prob = torch.sigmoid(logits).item()
        pred = 1 if prob >= 0.5 else 0

    return pred, prob

NameError: name 'predict' is not defined